### ISSUE TITLE
flavor の訳: フレーバー vs インスタンス種別

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/horizon#1]
ops-guide では、flavor の訳は「フレーバー」にしたが、
Horizon では インスタンスタイプ、インスタンス種別、になっている。
フレーバーに統一した方がいいかもしれない。

**Comment by ghost** [comment]
「フレーバー」に一票です。

**Comment by amotoki** [comment]
新しい訳ではすべて「フレーバー」にしています。

結論は出ていなくて、訳している途中ですが、「インスタンスタイプ」にかなり違和感を感じたので、「フレーバー」に統一中です。

**Comment by amotoki** [comment]
「フレーバー」に統一しました。
