### ISSUE TITLE
一瞬違うメッセージが表示される

### ISSUE THREAD

**Issue by ghost** [openstack-ja/horizon#10]
一部の画面を表示した際に、一瞬違うメッセージが表示される。

例: http://157.7.133.23:13580/admin/instances/

画面表示直後は「1 項目の表示中」と表示されるが、すぐに「1 項目を表示中」に変わる。
変更後のメッセージが正しいもののため、実害は少ないが気になるため何とかしたい。

**Comment by amotoki** [comment]
該当の文字列は、Horizon と Horizon JavaScript の両方にあります。Horizon の方が最初に表示される文字列で、すぐに JavaScript の方の文字列で置き換えられます。Horizon の方の翻訳を修正したので、直っていると思います。

確認できたらクローズしてください。
