### ISSUE TITLE
インスタンスの編集のウィンドウ

### ISSUE THREAD

**Issue by myamamot** [openstack-ja/horizon#11]
ここで報告するべきか分からないのですが、
セキュリティグループのタブのフィルターのフィールドがはみ出しています。

![instance-edit](https://f.cloud.github.com/assets/5043180/2479651/904d1394-b09e-11e3-9940-e4b5c8c60c14.png)

**Comment by amotoki** [comment]
Horizon 自体の問題だと思います。英語の場合は文字列が短いので発生していませんが、おそらく見出しの文字列を長くすると発生すると思います。

**Comment by amotoki** [comment]
https://bugs.launchpad.net/horizon/+bug/1288402

**Comment by amotoki** [comment]
Fixed in Juno and backported to Icehouse.
