### ISSUE TITLE
インスタンスのXXX　vs インスタンスをXXX

### ISSUE THREAD

**Issue by myamamot** [openstack-ja/horizon#12]
インスタンスの部分で、
![instance](https://f.cloud.github.com/assets/5043180/2479798/fb4f8880-b0a2-11e3-8ccd-87006986d3f6.png)

![volume](https://f.cloud.github.com/assets/5043180/2479812/96359d4e-b0a3-11e3-9b7b-a0c2d2e25df0.png)

インスタンスの編集
インスタンスを一時停止
インスタンスを休止
インスタンスのリサイズ
インスタンスをソフトリブート
インスタンスをハードリブート
インスタンスをシャットダウン
インスタンスの再作成
インスタンスを終了

ボリュームを削除
ボリュームのスナップショットを削除　（これは　ボリュームのスナップショット削除？）
イメージを削除
セキュリティグループを削除
ルールを削除
ルーターを削除
ゲートウェイを削除
プールを削除

「の」と「を」が混在しています。　インスタンスを終了、インスタンスをシャットダウンなど　をクリックすると、　「インスタンスを終了の確認」　という確認画面がでてくるので　「の」に統一するのはいかがでしょうか？

**Comment by amotoki** [comment]
何日か前に「の」に統一したと思います。

"%(action)s %(data_type)s" という文字列が、表のアクションの文字列、確認画面、アクション終了後のメッセージの３箇所で使用されていて、Havana の際には区別する手段がなかったため、苦肉の策でうまくいきそうな文字列をあてはめていたと思います。Icehouse では、これを (最初の2つと最後の1つに) 区別できるようになったので、翻訳上も区別できるようになりました。翻訳が更新されていなかっただけだと思います。

**Comment by amotoki** [comment]
全部を確認したわけではありませんので、Close しないでそのままにしておきます。
問題なければクローズしてください。

**Comment by amotoki** [comment]
上に挙がっているものは直っているので、クローズします。
