### ISSUE TITLE
宛先IPアドレス　VS 送信先IPアドレス

### ISSUE THREAD

**Issue by myamamot** [openstack-ja/horizon#13]
送信元IPアドレス　送信元ポート番号　Source IP address
宛先IPアドレス　宛先ポート番号　Destination IP address

送信元　と対で　送信先　とするのはいかがでしょうか？

**Comment by amotoki** [comment]
通信の世界では「宛先」を使うことが多いように思います。郵便の届け先と同じ意味で使われているので、「宛先」なのかなと思っています。自分はいつも「宛先」を使っています。

Horizon の翻訳を確認したところ、（自分が訳したところがおおいためか）一箇所以外は「宛先」になっていました。残りの一箇所も、訳の揺れでそうなっていました。

**Comment by amotoki** [comment]
とりあえず「宛先」で統一されているので、それで進めます。

**Comment by myamamot** [comment]
コメントありがとうございました。
了解です！
