### ISSUE TITLE
インスタンス > コンソールタブ > インスタンスのコンソールの画面の未翻訳の文字列

### ISSUE THREAD

**Issue by ykatabam** [openstack-ja/horizon#14]
もうご存知だと思いますが、"Connected (unencrypted) to QEMU (instance-0000001)"
 と "Send CtrolAltDel" が未翻訳だったので、ご報告させていただきました。

**Comment by amotoki** [comment]
翻訳されていないのは知っています。
Horizon の中で生成されている文字列ではないので、Horizon の翻訳では制御できません。
個人的にはそのままでいいかなと考えています。

VNC 表示のどこかで行われているはずですが、調査していません。noVNC, nova-novncproxy, libvirt, qemu (VMが動作するプロセス)  などが関係していますが、noVNC および nova には関連する文字列がないことは確認済みです。instance-00000001 というのは、nova が立ち上げる VM に割り当てられる VM の名前ですが、Nova API には現れない名前なので、おそらく qemu が生成していると考えています。

**Comment by ykatabam** [comment]
了解しました。ご丁寧にご説明いただき、ありがとうございました。

**Comment by amotoki** [comment]
クローズします。
