### ISSUE TITLE
&lt;start_ip_address&gt; がそのまま表示される

### ISSUE THREAD

**Issue by ghost** [openstack-ja/horizon#16]
翻訳文の「&lt;start_ip_address&gt;」がそのまま表示される。
英語でもそのまま表示されているため、ソースの問題と思われる。
二重にエスケープしていないか調査が必要。

**Comment by amotoki** [comment]
Icehouse version の話でしょうか？ 今頃気づきました。
horizon git repo (2014.1.2) に含まれる django.po を見る限り、
どちらもエスケープされており、正常に見えます。
何が問題か分かりませんでした。

```
#: dashboards/project/networks/workflows.py:171
msgid ""
"IP address allocation pools. Each entry is "
"&lt;start_ip_address&gt;,&lt;end_ip_address&gt; (e.g., "
"192.168.1.100,192.168.1.120) and one entry per line."
msgstr "IP アドレス割り当てプール。&lt;start_ip_address&gt;,&lt;end_ip_address&gt; (例: 192.168.1.100,192.168.1.120) 形式で、各項目を 1 行につき 1 項目記入します。"
```

**Comment by ghost** [comment]
私もすっかり忘れていました。。。
最新は確認できていませんが、ネットワークの作成画面で以下の表示になります。
エスケープされた文字列がさらにエスケープされているようです。
![ja](https://cloud.githubusercontent.com/assets/4470316/3885567/22cace22-21c5-11e4-95f1-6c2d9eca09ba.png)
![en](https://cloud.githubusercontent.com/assets/4470316/3885569/34b73a62-21c5-11e4-87eb-114916d260bd.png)

**Comment by amotoki** [comment]
オリジナルの文字列でエスケープされています。
Horizon では基本的に rendering 時にエスケープを行っているので、
ヘルプの文字列でエスケープをする必要はないですね。

なお、Juno では発生しません。 < > 自体が削除されています。

マイナーなので Icehouse で直すかどうかは微妙ですね。
修正した方がよさそうなら、Horizon にバグレポートしていただけませんか？
どちらでもよいと思います。

**Comment by ghost** [comment]
操作に支障があるような問題ではないため、Junoで発生しないということであれば、このままクローズしましょう。
