### ISSUE TITLE
role の訳 : 役割 vs ロール

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/horizon#2]
"role" の訳として 「役割」と「ロール」の両方の訳がある。
Havana では "role" の管理画面もできているので、登場回数が増える。
同じ用語で訳が混在しているとよくないので、最低限統一する必要がある。

**Comment by ghost** [comment]
かなり迷いますが、「役割」に一票です。
どちらにしても、統一することが重要だと思います。

**Comment by amotoki** [comment]
個人的には「ロール」に一票です。

日本語の「役割」はいろいろな意味がありますし、「ロール」は他の構成管理ツール (Chef など) でも使われているので「ロール」で十分通じるだろうというのが理由です。

**Comment by ghost** [comment]
最終結論が出るまでは「ロール」に統一する方向で進めましょうか。

**Comment by amotoki** [comment]
とりあえず「ロール」に統一したもので、Havana 向けには進めましょう。
