### ISSUE TITLE
「下さい」vs「ください」

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/horizon#4]
両方混在しています。

**Comment by ghost** [comment]
以下のサイトによると、「○○を下さい」と「○○してください」が正しいようです。

http://www.koho.or.jp/useful/qa/hyouki/hyouki06.html
http://www.nhk.or.jp/kininaru-blog/55134.html

**Comment by amotoki** [comment]
ありがとうございます。そういうガイドラインがあったのですね。

「～してください」のパターンだけでしたので、「ください」に統一しました。
