### ISSUE TITLE
disk write/read の訳の統一

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/horizon#6]
write/read の訳
- 書き込み、読み出し
- 書き出し、読み込み

などの対称関係をあまり考えずに訳しているので、多分混在しているはず。

**Comment by S-Kinjo** [comment]
個人的には、”読み込み / 書き込み"の方がスッキリします。

**Comment by amotoki** [comment]
個人的な好みとしては、一方が「〜込み」なら、もう一方は「〜出し」です。
「読み込む」「書き出す」のようにすると、「（メモリに）ディスクから読み込む」「（メモリから）ディスクに書き出す」に制御対象が一定になるので、こちらを好んで使っています。

意見では read/write で両方「〜込み」にするのは対象が変化している印象を持っています。
「読み込み」「書き込み」は、転送先に焦点があたっているように思っています。

あくまで主観ということで。

**Comment by amotoki** [comment]
現在は「書き込み」「読み出し」でほぼ統一されていると思います。
Havana の時点の話なので、いったんクローズします。
