### ISSUE TITLE
クオータ設定項目の"ギガバイト"の対象が不明

### ISSUE THREAD

**Issue by torumakabe** [openstack-ja/horizon#9]
管理メニュー→システムパネル→デフォルト値の内にあるクオータ設定項目の"ギガバイト"の対象が明記されておらず、分かりにくい。原文の修正が必要か。

**Comment by amotoki** [comment]
同感です。 https://bugs.launchpad.net/horizon/+bug/1298934 で修正します。

**Comment by amotoki** [comment]
修正パッチがマージされて、翻訳も対応したのでクローズします。

**Comment by torumakabe** [comment]
確認しました。ありがとうございます！
